use_frameworks!

platform :ios, '8.0'

target 'CDAddressPickView_Example' do
  pod 'CDAddressPickView', :path => '../'

  target 'CDAddressPickView_Tests' do
    inherit! :search_paths

    
  end
end
